/*
API Reference for Tableau Resource Versioned RESTful Endpoints

>The following OpenAPI documentation describes the details of the new Tableau RESTful APIs. A growing number of these are  being released alongside more than 150 [classic REST endpoints](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm)  that are currently in wide usage in the Tableau community.    >There are some differences users of the classic endpoints will recognize when viewing these new endpoints. Request bodies for these new REST endpoints must  be formatted using JSON. Endpoint URIs don't contain an API version number. For more information, see  [REST API and Resource Versions](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm).   ![tableau platform](https://github.com/stephenlprice/tableau-rest-openapi/blob/main/assets/images/tableau-platform.png?raw=true)

API version: 2021.2
Contact: stellopricint@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TableauAnalyticsextensionsV1ConnectionList struct for TableauAnalyticsextensionsV1ConnectionList
type TableauAnalyticsextensionsV1ConnectionList struct {
	ConnectionList []TableauAnalyticsextensionsV1ConnectionItem `json:"connectionList,omitempty"`
}

// NewTableauAnalyticsextensionsV1ConnectionList instantiates a new TableauAnalyticsextensionsV1ConnectionList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableauAnalyticsextensionsV1ConnectionList() *TableauAnalyticsextensionsV1ConnectionList {
	this := TableauAnalyticsextensionsV1ConnectionList{}
	return &this
}

// NewTableauAnalyticsextensionsV1ConnectionListWithDefaults instantiates a new TableauAnalyticsextensionsV1ConnectionList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableauAnalyticsextensionsV1ConnectionListWithDefaults() *TableauAnalyticsextensionsV1ConnectionList {
	this := TableauAnalyticsextensionsV1ConnectionList{}
	return &this
}

// GetConnectionList returns the ConnectionList field value if set, zero value otherwise.
func (o *TableauAnalyticsextensionsV1ConnectionList) GetConnectionList() []TableauAnalyticsextensionsV1ConnectionItem {
	if o == nil || o.ConnectionList == nil {
		var ret []TableauAnalyticsextensionsV1ConnectionItem
		return ret
	}
	return o.ConnectionList
}

// GetConnectionListOk returns a tuple with the ConnectionList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableauAnalyticsextensionsV1ConnectionList) GetConnectionListOk() ([]TableauAnalyticsextensionsV1ConnectionItem, bool) {
	if o == nil || o.ConnectionList == nil {
		return nil, false
	}
	return o.ConnectionList, true
}

// HasConnectionList returns a boolean if a field has been set.
func (o *TableauAnalyticsextensionsV1ConnectionList) HasConnectionList() bool {
	if o != nil && o.ConnectionList != nil {
		return true
	}

	return false
}

// SetConnectionList gets a reference to the given []TableauAnalyticsextensionsV1ConnectionItem and assigns it to the ConnectionList field.
func (o *TableauAnalyticsextensionsV1ConnectionList) SetConnectionList(v []TableauAnalyticsextensionsV1ConnectionItem) {
	o.ConnectionList = v
}

func (o TableauAnalyticsextensionsV1ConnectionList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ConnectionList != nil {
		toSerialize["connectionList"] = o.ConnectionList
	}
	return json.Marshal(toSerialize)
}

type NullableTableauAnalyticsextensionsV1ConnectionList struct {
	value *TableauAnalyticsextensionsV1ConnectionList
	isSet bool
}

func (v NullableTableauAnalyticsextensionsV1ConnectionList) Get() *TableauAnalyticsextensionsV1ConnectionList {
	return v.value
}

func (v *NullableTableauAnalyticsextensionsV1ConnectionList) Set(val *TableauAnalyticsextensionsV1ConnectionList) {
	v.value = val
	v.isSet = true
}

func (v NullableTableauAnalyticsextensionsV1ConnectionList) IsSet() bool {
	return v.isSet
}

func (v *NullableTableauAnalyticsextensionsV1ConnectionList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableauAnalyticsextensionsV1ConnectionList(val *TableauAnalyticsextensionsV1ConnectionList) *NullableTableauAnalyticsextensionsV1ConnectionList {
	return &NullableTableauAnalyticsextensionsV1ConnectionList{value: val, isSet: true}
}

func (v NullableTableauAnalyticsextensionsV1ConnectionList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableauAnalyticsextensionsV1ConnectionList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


