/*
API Reference for Tableau Resource Versioned RESTful Endpoints

>The following OpenAPI documentation describes the details of the new Tableau RESTful APIs. A growing number of these are  being released alongside more than 150 [classic REST endpoints](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm)  that are currently in wide usage in the Tableau community.    >There are some differences users of the classic endpoints will recognize when viewing these new endpoints. Request bodies for these new REST endpoints must  be formatted using JSON. Endpoint URIs don't contain an API version number. For more information, see  [REST API and Resource Versions](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm).   ![tableau platform](https://github.com/stephenlprice/tableau-rest-openapi/blob/main/assets/images/tableau-platform.png?raw=true)

API version: 2021.2
Contact: stellopricint@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TableauAnalyticsextensionsV1ConnectionMetadata struct for TableauAnalyticsextensionsV1ConnectionMetadata
type TableauAnalyticsextensionsV1ConnectionMetadata struct {
	ConnectionLuid *string `json:"connection_luid,omitempty"`
	ConnectionBrief *TableauAnalyticsextensionsV1ConnectionBrief `json:"connection_brief,omitempty"`
}

// NewTableauAnalyticsextensionsV1ConnectionMetadata instantiates a new TableauAnalyticsextensionsV1ConnectionMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableauAnalyticsextensionsV1ConnectionMetadata() *TableauAnalyticsextensionsV1ConnectionMetadata {
	this := TableauAnalyticsextensionsV1ConnectionMetadata{}
	return &this
}

// NewTableauAnalyticsextensionsV1ConnectionMetadataWithDefaults instantiates a new TableauAnalyticsextensionsV1ConnectionMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableauAnalyticsextensionsV1ConnectionMetadataWithDefaults() *TableauAnalyticsextensionsV1ConnectionMetadata {
	this := TableauAnalyticsextensionsV1ConnectionMetadata{}
	return &this
}

// GetConnectionLuid returns the ConnectionLuid field value if set, zero value otherwise.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) GetConnectionLuid() string {
	if o == nil || o.ConnectionLuid == nil {
		var ret string
		return ret
	}
	return *o.ConnectionLuid
}

// GetConnectionLuidOk returns a tuple with the ConnectionLuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) GetConnectionLuidOk() (*string, bool) {
	if o == nil || o.ConnectionLuid == nil {
		return nil, false
	}
	return o.ConnectionLuid, true
}

// HasConnectionLuid returns a boolean if a field has been set.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) HasConnectionLuid() bool {
	if o != nil && o.ConnectionLuid != nil {
		return true
	}

	return false
}

// SetConnectionLuid gets a reference to the given string and assigns it to the ConnectionLuid field.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) SetConnectionLuid(v string) {
	o.ConnectionLuid = &v
}

// GetConnectionBrief returns the ConnectionBrief field value if set, zero value otherwise.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) GetConnectionBrief() TableauAnalyticsextensionsV1ConnectionBrief {
	if o == nil || o.ConnectionBrief == nil {
		var ret TableauAnalyticsextensionsV1ConnectionBrief
		return ret
	}
	return *o.ConnectionBrief
}

// GetConnectionBriefOk returns a tuple with the ConnectionBrief field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) GetConnectionBriefOk() (*TableauAnalyticsextensionsV1ConnectionBrief, bool) {
	if o == nil || o.ConnectionBrief == nil {
		return nil, false
	}
	return o.ConnectionBrief, true
}

// HasConnectionBrief returns a boolean if a field has been set.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) HasConnectionBrief() bool {
	if o != nil && o.ConnectionBrief != nil {
		return true
	}

	return false
}

// SetConnectionBrief gets a reference to the given TableauAnalyticsextensionsV1ConnectionBrief and assigns it to the ConnectionBrief field.
func (o *TableauAnalyticsextensionsV1ConnectionMetadata) SetConnectionBrief(v TableauAnalyticsextensionsV1ConnectionBrief) {
	o.ConnectionBrief = &v
}

func (o TableauAnalyticsextensionsV1ConnectionMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ConnectionLuid != nil {
		toSerialize["connection_luid"] = o.ConnectionLuid
	}
	if o.ConnectionBrief != nil {
		toSerialize["connection_brief"] = o.ConnectionBrief
	}
	return json.Marshal(toSerialize)
}

type NullableTableauAnalyticsextensionsV1ConnectionMetadata struct {
	value *TableauAnalyticsextensionsV1ConnectionMetadata
	isSet bool
}

func (v NullableTableauAnalyticsextensionsV1ConnectionMetadata) Get() *TableauAnalyticsextensionsV1ConnectionMetadata {
	return v.value
}

func (v *NullableTableauAnalyticsextensionsV1ConnectionMetadata) Set(val *TableauAnalyticsextensionsV1ConnectionMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableTableauAnalyticsextensionsV1ConnectionMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableTableauAnalyticsextensionsV1ConnectionMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableauAnalyticsextensionsV1ConnectionMetadata(val *TableauAnalyticsextensionsV1ConnectionMetadata) *NullableTableauAnalyticsextensionsV1ConnectionMetadata {
	return &NullableTableauAnalyticsextensionsV1ConnectionMetadata{value: val, isSet: true}
}

func (v NullableTableauAnalyticsextensionsV1ConnectionMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableauAnalyticsextensionsV1ConnectionMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


