/**
 * API Reference for Tableau Resource Versioned RESTful Endpoints
 * >The following OpenAPI documentation describes the details of the new Tableau RESTful APIs. A growing number of these are  being released alongside more than 150 [classic REST endpoints](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm)  that are currently in wide usage in the Tableau community.    >There are some differences users of the classic endpoints will recognize when viewing these new endpoints. Request bodies for these new REST endpoints must  be formatted using JSON. Endpoint URIs don't contain an API version number. For more information, see  [REST API and Resource Versions](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm).   ![tableau platform](https://github.com/stephenlprice/tableau-rest-openapi/blob/main/assets/images/tableau-platform.png?raw=true)
 *
 * The version of the OpenAPI document: 2021.2
 * Contact: stellopricint@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TableauExtensionsDashboardV1BlockListItem from './TableauExtensionsDashboardV1BlockListItem';

/**
 * The TableauExtensionsDashboardV1ServerSettings model module.
 * @module model/TableauExtensionsDashboardV1ServerSettings
 * @version 2021.2
 */
class TableauExtensionsDashboardV1ServerSettings {
    /**
     * Constructs a new <code>TableauExtensionsDashboardV1ServerSettings</code>.
     * Extension settings of a Tableau server.
     * @alias module:model/TableauExtensionsDashboardV1ServerSettings
     */
    constructor() { 
        
        TableauExtensionsDashboardV1ServerSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableauExtensionsDashboardV1ServerSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableauExtensionsDashboardV1ServerSettings} obj Optional instance to populate.
     * @return {module:model/TableauExtensionsDashboardV1ServerSettings} The populated <code>TableauExtensionsDashboardV1ServerSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableauExtensionsDashboardV1ServerSettings();

            if (data.hasOwnProperty('block_list_items')) {
                obj['block_list_items'] = ApiClient.convertToType(data['block_list_items'], [TableauExtensionsDashboardV1BlockListItem]);
            }
            if (data.hasOwnProperty('extensions_enabled')) {
                obj['extensions_enabled'] = ApiClient.convertToType(data['extensions_enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TableauExtensionsDashboardV1BlockListItem>} block_list_items
 */
TableauExtensionsDashboardV1ServerSettings.prototype['block_list_items'] = undefined;

/**
 * Specifies whether sandboxed extensions are allowed to run on the site.
 * @member {Boolean} extensions_enabled
 */
TableauExtensionsDashboardV1ServerSettings.prototype['extensions_enabled'] = undefined;






export default TableauExtensionsDashboardV1ServerSettings;

