/**
 * API Reference for Tableau Resource Versioned RESTful Endpoints
 * >The following OpenAPI documentation describes the details of the new Tableau RESTful APIs. A growing number of these are  being released alongside more than 150 [classic REST endpoints](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm)  that are currently in wide usage in the Tableau community.    >There are some differences users of the classic endpoints will recognize when viewing these new endpoints. Request bodies for these new REST endpoints must  be formatted using JSON. Endpoint URIs don't contain an API version number. For more information, see  [REST API and Resource Versions](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm).   ![tableau platform](https://github.com/stephenlprice/tableau-rest-openapi/blob/main/assets/images/tableau-platform.png?raw=true)
 *
 * The version of the OpenAPI document: 2021.2
 * Contact: stellopricint@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TableauExtensionsDashboardV1SafeListItem from './TableauExtensionsDashboardV1SafeListItem';

/**
 * The TableauExtensionsDashboardV1SafeListItems model module.
 * @module model/TableauExtensionsDashboardV1SafeListItems
 * @version 2021.2
 */
class TableauExtensionsDashboardV1SafeListItems {
    /**
     * Constructs a new <code>TableauExtensionsDashboardV1SafeListItems</code>.
     * A list of dashboard extensions allowed to run on a site.
     * @alias module:model/TableauExtensionsDashboardV1SafeListItems
     */
    constructor() { 
        
        TableauExtensionsDashboardV1SafeListItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableauExtensionsDashboardV1SafeListItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableauExtensionsDashboardV1SafeListItems} obj Optional instance to populate.
     * @return {module:model/TableauExtensionsDashboardV1SafeListItems} The populated <code>TableauExtensionsDashboardV1SafeListItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableauExtensionsDashboardV1SafeListItems();

            if (data.hasOwnProperty('safe_list_items')) {
                obj['safe_list_items'] = ApiClient.convertToType(data['safe_list_items'], [TableauExtensionsDashboardV1SafeListItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TableauExtensionsDashboardV1SafeListItem>} safe_list_items
 */
TableauExtensionsDashboardV1SafeListItems.prototype['safe_list_items'] = undefined;






export default TableauExtensionsDashboardV1SafeListItems;

