/**
 * API Reference for Tableau Resource Versioned RESTful Endpoints
 * >The following OpenAPI documentation describes the details of the new Tableau RESTful APIs. A growing number of these are  being released alongside more than 150 [classic REST endpoints](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm)  that are currently in wide usage in the Tableau community.    >There are some differences users of the classic endpoints will recognize when viewing these new endpoints. Request bodies for these new REST endpoints must  be formatted using JSON. Endpoint URIs don't contain an API version number. For more information, see  [REST API and Resource Versions](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm).   ![tableau platform](https://github.com/stephenlprice/tableau-rest-openapi/blob/main/assets/images/tableau-platform.png?raw=true)
 *
 * The version of the OpenAPI document: 2021.2
 * Contact: stellopricint@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TableauAnalyticsextensionsV1ConnectionBrief model module.
 * @module model/TableauAnalyticsextensionsV1ConnectionBrief
 * @version 2021.2
 */
class TableauAnalyticsextensionsV1ConnectionBrief {
    /**
     * Constructs a new <code>TableauAnalyticsextensionsV1ConnectionBrief</code>.
     * @alias module:model/TableauAnalyticsextensionsV1ConnectionBrief
     */
    constructor() { 
        
        TableauAnalyticsextensionsV1ConnectionBrief.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TableauAnalyticsextensionsV1ConnectionBrief</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TableauAnalyticsextensionsV1ConnectionBrief} obj Optional instance to populate.
     * @return {module:model/TableauAnalyticsextensionsV1ConnectionBrief} The populated <code>TableauAnalyticsextensionsV1ConnectionBrief</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TableauAnalyticsextensionsV1ConnectionBrief();

            if (data.hasOwnProperty('connection_name')) {
                obj['connection_name'] = ApiClient.convertToType(data['connection_name'], 'String');
            }
            if (data.hasOwnProperty('connection_type')) {
                obj['connection_type'] = ApiClient.convertToType(data['connection_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Required. The title of the connection.
 * @member {String} connection_name
 */
TableauAnalyticsextensionsV1ConnectionBrief.prototype['connection_name'] = undefined;

/**
 * Required. The kind of service responding to analytics extension requests. The value can be: TABPY, for a [Tableau TabPy](https://github.com/tableau/TabPy) server; GENERIC_API for your custom service that complies with the [Analytics Extensions API spec](https://tableau.github.io/analytics-extensions-api/docs/ae_intro.html); or RSERVE, for an [Rserve](https://www.tableau.com/solutions/r) service; or EINSTEIN_DISCOVERY for your instance of [Einstein Discovery](https://help.tableau.com/current/server-linux/en-us/config_r_tabpy.htm).
 * @member {module:model/TableauAnalyticsextensionsV1ConnectionBrief.ConnectionTypeEnum} connection_type
 */
TableauAnalyticsextensionsV1ConnectionBrief.prototype['connection_type'] = undefined;





/**
 * Allowed values for the <code>connection_type</code> property.
 * @enum {String}
 * @readonly
 */
TableauAnalyticsextensionsV1ConnectionBrief['ConnectionTypeEnum'] = {

    /**
     * value: "UNDEFINED"
     * @const
     */
    "UNDEFINED": "UNDEFINED",

    /**
     * value: "TABPY"
     * @const
     */
    "TABPY": "TABPY",

    /**
     * value: "RSERVE"
     * @const
     */
    "RSERVE": "RSERVE",

    /**
     * value: "EINSTEIN_DISCOVERY"
     * @const
     */
    "EINSTEIN_DISCOVERY": "EINSTEIN_DISCOVERY",

    /**
     * value: "GENERIC_API"
     * @const
     */
    "GENERIC_API": "GENERIC_API"
};



export default TableauAnalyticsextensionsV1ConnectionBrief;

