/*
 * API Reference for Tableau Resource Versioned RESTful Endpoints
 * >The following OpenAPI documentation describes the details of the new Tableau RESTful APIs. A growing number of these are  being released alongside more than 150 [classic REST endpoints](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm)  that are currently in wide usage in the Tableau community.    >There are some differences users of the classic endpoints will recognize when viewing these new endpoints. Request bodies for these new REST endpoints must  be formatted using JSON. Endpoint URIs don't contain an API version number. For more information, see  [REST API and Resource Versions](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm).   ![tableau platform](https://github.com/stephenlprice/tableau-rest-openapi/blob/main/assets/images/tableau-platform.png?raw=true)
 *
 * The version of the OpenAPI document: 2021.2
 * Contact: stellopricint@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TableauAnalyticsextensionsV1ConnectionMetadata;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TableauAnalyticsextensionsV1ConnectionMetadataList
 */
public class TableauAnalyticsextensionsV1ConnectionMetadataListTest {
    private final TableauAnalyticsextensionsV1ConnectionMetadataList model = new TableauAnalyticsextensionsV1ConnectionMetadataList();

    /**
     * Model tests for TableauAnalyticsextensionsV1ConnectionMetadataList
     */
    @Test
    public void testTableauAnalyticsextensionsV1ConnectionMetadataList() {
        // TODO: test TableauAnalyticsextensionsV1ConnectionMetadataList
    }

    /**
     * Test the property 'connectionMetadataList'
     */
    @Test
    public void connectionMetadataListTest() {
        // TODO: test connectionMetadataList
    }

}
