/**
 * API Reference for Tableau Resource Versioned RESTful Endpoints
 * >The following OpenAPI documentation describes the details of the new Tableau RESTful APIs. A growing number of these are  being released alongside more than 150 [classic REST endpoints](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm)  that are currently in wide usage in the Tableau community.    >There are some differences users of the classic endpoints will recognize when viewing these new endpoints. Request bodies for these new REST endpoints must  be formatted using JSON. Endpoint URIs don't contain an API version number. For more information, see  [REST API and Resource Versions](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm).   ![tableau platform](https://github.com/stephenlprice/tableau-rest-openapi/blob/main/assets/images/tableau-platform.png?raw=true)
 *
 * The version of the OpenAPI document: 2021.2
 * Contact: stellopricint@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import TableauAnalyticsextensionsV1ConnectionBrief from './model/TableauAnalyticsextensionsV1ConnectionBrief';
import TableauAnalyticsextensionsV1ConnectionItem from './model/TableauAnalyticsextensionsV1ConnectionItem';
import TableauAnalyticsextensionsV1ConnectionList from './model/TableauAnalyticsextensionsV1ConnectionList';
import TableauAnalyticsextensionsV1ConnectionMapping from './model/TableauAnalyticsextensionsV1ConnectionMapping';
import TableauAnalyticsextensionsV1ConnectionMetadata from './model/TableauAnalyticsextensionsV1ConnectionMetadata';
import TableauAnalyticsextensionsV1ConnectionMetadataList from './model/TableauAnalyticsextensionsV1ConnectionMetadataList';
import TableauAnalyticsextensionsV1ServerSettings from './model/TableauAnalyticsextensionsV1ServerSettings';
import TableauAnalyticsextensionsV1SiteSettings from './model/TableauAnalyticsextensionsV1SiteSettings';
import TableauExtensionsDashboardV1BlockListItem from './model/TableauExtensionsDashboardV1BlockListItem';
import TableauExtensionsDashboardV1BlockListItems from './model/TableauExtensionsDashboardV1BlockListItems';
import TableauExtensionsDashboardV1SafeListItem from './model/TableauExtensionsDashboardV1SafeListItem';
import TableauExtensionsDashboardV1SafeListItems from './model/TableauExtensionsDashboardV1SafeListItems';
import TableauExtensionsDashboardV1ServerSettings from './model/TableauExtensionsDashboardV1ServerSettings';
import TableauExtensionsDashboardV1SiteSettings from './model/TableauExtensionsDashboardV1SiteSettings';
import AnalyticsExtensionsSettingsMethodsApi from './api/AnalyticsExtensionsSettingsMethodsApi';
import DashboardExtensionsSettingsMethodsApi from './api/DashboardExtensionsSettingsMethodsApi';


/**
* The_following_OpenAPI_documentation_describes_the_details_of_the_new_Tableau_RESTful_APIs__A_growing_number_of_these_are__being_released_alongside_more_than_150__classic_REST_endpoints_https__help_tableau_com_current_api_rest_api_en_us_REST_rest_api_ref_htm__that_are_currently_in_wide_usage_in_the_Tableau_community___There_are_some_differences_users_of_the_classic_endpoints_will_recognize_when_viewing_these_new_endpoints__Request_bodies_for_these_new_REST_endpoints_must__be_formatted_using_JSON__Endpoint_URIs_dont_contain_an_API_version_number__For_more_information_see___REST_API_and_Resource_Versions_https__help_tableau_com_current_api_rest_api_en_us_REST_rest_api_concepts_versions_htm___tableau_platform_https__github_com_stephenlprice_tableau_rest_openapi_blob_main_assets_images_tableau_platform_pngrawtrue.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiReferenceForTableauResourceVersionedResTfulEndpoints = require('index'); // See note below*.
* var xxxSvc = new ApiReferenceForTableauResourceVersionedResTfulEndpoints.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiReferenceForTableauResourceVersionedResTfulEndpoints.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiReferenceForTableauResourceVersionedResTfulEndpoints.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiReferenceForTableauResourceVersionedResTfulEndpoints.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2021.2
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The TableauAnalyticsextensionsV1ConnectionBrief model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1ConnectionBrief}
     */
    TableauAnalyticsextensionsV1ConnectionBrief,

    /**
     * The TableauAnalyticsextensionsV1ConnectionItem model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1ConnectionItem}
     */
    TableauAnalyticsextensionsV1ConnectionItem,

    /**
     * The TableauAnalyticsextensionsV1ConnectionList model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1ConnectionList}
     */
    TableauAnalyticsextensionsV1ConnectionList,

    /**
     * The TableauAnalyticsextensionsV1ConnectionMapping model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1ConnectionMapping}
     */
    TableauAnalyticsextensionsV1ConnectionMapping,

    /**
     * The TableauAnalyticsextensionsV1ConnectionMetadata model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1ConnectionMetadata}
     */
    TableauAnalyticsextensionsV1ConnectionMetadata,

    /**
     * The TableauAnalyticsextensionsV1ConnectionMetadataList model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1ConnectionMetadataList}
     */
    TableauAnalyticsextensionsV1ConnectionMetadataList,

    /**
     * The TableauAnalyticsextensionsV1ServerSettings model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1ServerSettings}
     */
    TableauAnalyticsextensionsV1ServerSettings,

    /**
     * The TableauAnalyticsextensionsV1SiteSettings model constructor.
     * @property {module:model/TableauAnalyticsextensionsV1SiteSettings}
     */
    TableauAnalyticsextensionsV1SiteSettings,

    /**
     * The TableauExtensionsDashboardV1BlockListItem model constructor.
     * @property {module:model/TableauExtensionsDashboardV1BlockListItem}
     */
    TableauExtensionsDashboardV1BlockListItem,

    /**
     * The TableauExtensionsDashboardV1BlockListItems model constructor.
     * @property {module:model/TableauExtensionsDashboardV1BlockListItems}
     */
    TableauExtensionsDashboardV1BlockListItems,

    /**
     * The TableauExtensionsDashboardV1SafeListItem model constructor.
     * @property {module:model/TableauExtensionsDashboardV1SafeListItem}
     */
    TableauExtensionsDashboardV1SafeListItem,

    /**
     * The TableauExtensionsDashboardV1SafeListItems model constructor.
     * @property {module:model/TableauExtensionsDashboardV1SafeListItems}
     */
    TableauExtensionsDashboardV1SafeListItems,

    /**
     * The TableauExtensionsDashboardV1ServerSettings model constructor.
     * @property {module:model/TableauExtensionsDashboardV1ServerSettings}
     */
    TableauExtensionsDashboardV1ServerSettings,

    /**
     * The TableauExtensionsDashboardV1SiteSettings model constructor.
     * @property {module:model/TableauExtensionsDashboardV1SiteSettings}
     */
    TableauExtensionsDashboardV1SiteSettings,

    /**
    * The AnalyticsExtensionsSettingsMethodsApi service constructor.
    * @property {module:api/AnalyticsExtensionsSettingsMethodsApi}
    */
    AnalyticsExtensionsSettingsMethodsApi,

    /**
    * The DashboardExtensionsSettingsMethodsApi service constructor.
    * @property {module:api/DashboardExtensionsSettingsMethodsApi}
    */
    DashboardExtensionsSettingsMethodsApi
};
